[package]
name = "cjuggler"
version = "0.1.0"
edition = "2021"
authors = ["0x4ndy <andy@andy.codes>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.34"
serde = { version="1.0", features = ["derive"] }
serde_json = "1.0"
